Bug 1555776 - Turn on artifact-based indexing info for mozilla-release.
This is just copying the mozilla-beta setup to mozilla-release, with
s/beta/release/

diff --git a/mozilla-release/setup b/mozilla-release/setup
--- a/mozilla-release/setup
+++ b/mozilla-release/setup
@@ -6,8 +6,28 @@ set -o pipefail # Check all commands in a pipeline
 
 # See ../mozilla-central/setup for documentation
 
+REVISION_TREE=mozilla-release
+REVISION_ID=latest
+TRY_GIT_REV=
+export INDEX_RUSTLIB=no # until the m-c patches for bug 1545968 ride the trains to release
+
 date
 
-$CONFIG_REPO/shared/checkout-gecko-repos.sh "release" ""
+source $CONFIG_REPO/shared/resolve-gecko-revs.sh $REVISION_TREE $REVISION_ID
 
 date
+
+$CONFIG_REPO/shared/checkout-gecko-repos.sh "release" "$INDEXED_GIT_REV"
+
+date
+
+if [ -n "$INDEXED_GIT_REV" ]; then
+    pushd $INDEX_ROOT
+    $CONFIG_REPO/shared/fetch-tc-artifacts.sh $REVISION_TREE $INDEXED_HG_REV
+    popd
+
+    date
+else
+    echo "ERROR: Unable to find git equivalent for hg rev $INDEXED_HG_REV; please fix the mapper and retry."
+    exit 1
+fi
