Bug 1549592 - Fail earlier and with a better error message if revision mapping fails

diff --git a/mozilla-central/setup b/mozilla-central/setup
--- a/mozilla-central/setup
+++ b/mozilla-central/setup
@@ -34,7 +34,8 @@ if [ -n "$INDEXED_GIT_REV" ]; then
 
     date
 else
-    echo "WARNING: Unable to find git equivalent for hg rev $INDEXED_HG_REV; omitting Rust/C++ analysis..."
+    echo "ERROR: Unable to find git equivalent for hg rev $INDEXED_HG_REV; please fix the mapper and retry."
+    exit 1
 fi
 
 # Also generate blame for some other branches, because the gecko-blame repo is
